---
caching:
  expires: 3600
db:
  fb:
    adapter: mysql2
    encoding: utf8
    host: localhost
    username: root
    password:
    port: 3306
    database: fbapp_mirror
  slb:
    adapter: mysql2
    encoding: utf8
    host: localhost
    username: root
    password:
    port: 3306
    database: slbapp
