---
caching:
  expires: 3600
db:
  fb_201505:
    adapter: mysql2
    encoding: utf8
    host: mysql
    username: root
    password: root
    port: 3306
    database: fbapp
  fb_201604:
    adapter: mysql2
    encoding: utf8
    host: mysql
    username: root
    password: root
    port: 3306
    database: fbapp_mirror
  fb_201703:
    adapter: mysql2
    encoding: utf8
    host: mysql
    username: root
    password: root
    port: 3306
    database: fbapp_201703
  fb_201712:
    adapter: mysql2
    encoding: utf8
    host: mysql
    username: root
    password: root
    port: 3306
    database: fbapp_201712
  fb_201809:
    adapter: mysql2
    encoding: utf8
    host: mysql
    username: root
    password: root
    port: 3306
    database: fbapp_201809
  slb:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp
  slb_201712:
    adapter: mysql2
    encoding: utf8
    host: sealifebase
    username: root
    password: root
    port: 3306
    database: slbapp_201712
