redis:
  image: redis
  restart: always
  volumes:
    - $HOME/volume/data/redis:/data
  command:  redis-server --appendonly yes

fishbase:
  image: mariadb:10.4
  volumes:
    - $HOME/volume/data/fishbase:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  restart: always

sealifebase:
  image: mariadb:10.4
  volumes:
    - $HOME/volume/data/sealifebase:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  restart: always

api:
  image: sckott/fishbaseapi
  ports:
    - "8888:8888"
  links:
    - fishbase
    - sealifebase
    - redis

# nginx:
#   ports:
#     - 80:80
#   links:
#     - api
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf
#   image: nginx
